### ISSUE TITLE
TypeError: can't compare offset-naive and offset-aware datetimes

### ISSUE THREAD

**Issue by Mracobes9** [rvinzent/django-dynamic-models#11]
Hi. I try to execute  `ModelSchema.objects.get(name=dataset_name).as_model()._meta.db_table`, but i have error `TypeError: can't compare offset-naive and offset-aware datetimes`.
Full traceback: 
```
Traceback (most recent call last):
  File "/home/mracobes/univer/visualisator/.venv/lib/python3.7/site-packages/django/contrib/staticfiles/handlers.py", line 65, in __call__
    return self.application(environ, start_response)
  File "/home/mracobes/univer/visualisator/.venv/lib/python3.7/site-packages/django/core/handlers/wsgi.py", line 141, in __call__
    response = self.get_response(request)
  File "/home/mracobes/univer/visualisator/.venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 75, in get_response
    response = self._middleware_chain(request)
  File "/home/mracobes/univer/visualisator/.venv/lib/python3.7/site-packages/django/core/handlers/exception.py", line 36, in inner
    response = response_for_exception(request, exc)
  File "/home/mracobes/univer/visualisator/.venv/lib/python3.7/site-packages/django/core/handlers/exception.py", line 90, in response_for_exception
    response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
  File "/home/mracobes/univer/visualisator/.venv/lib/python3.7/site-packages/django/core/handlers/exception.py", line 125, in handle_uncaught_exception
    return debug.technical_500_response(request, *exc_info)
  File "/home/mracobes/univer/visualisator/.venv/lib/python3.7/site-packages/django_extensions/management/technical_response.py", line 37, in null_technical_500_response
    six.reraise(exc_type, exc_value, tb)
  File "/home/mracobes/univer/visualisator/.venv/lib/python3.7/site-packages/six.py", line 692, in reraise
    raise value.with_traceback(tb)
  File "/home/mracobes/univer/visualisator/.venv/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/mracobes/univer/visualisator/.venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/mracobes/univer/visualisator/.venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/mracobes/univer/visualisator/.venv/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/mracobes/univer/visualisator/.venv/lib/python3.7/site-packages/rest_framework/viewsets.py", line 114, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/mracobes/univer/visualisator/.venv/lib/python3.7/site-packages/rest_framework/views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "/home/mracobes/univer/visualisator/.venv/lib/python3.7/site-packages/rest_framework/views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/mracobes/univer/visualisator/.venv/lib/python3.7/site-packages/rest_framework/views.py", line 476, in raise_uncaught_exception
    raise exc
  File "/home/mracobes/univer/visualisator/.venv/lib/python3.7/site-packages/rest_framework/views.py", line 502, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/mracobes/univer/visualisator/old_metaphore/views/plot.py", line 16, in get_plot_data
    table_name = ModelSchema.objects.get(name=dataset_name).as_model()._meta.db_table
  File "/home/mracobes/univer/visualisator/.venv/lib/python3.7/site-packages/dynamic_models/models.py", line 152, in as_model
    return self.factory.get_model()
  File "/home/mracobes/univer/visualisator/.venv/lib/python3.7/site-packages/dynamic_models/factory.py", line 17, in get_model
    if registered and self.schema.is_current_model(registered):
  File "/home/mracobes/univer/visualisator/.venv/lib/python3.7/site-packages/dynamic_models/models.py", line 124, in is_current_model
    return model._declared >= self.last_modified
TypeError: can't compare offset-naive and offset-aware datetimes


```

**Comment by HiteshSachdev** [comment]
You need to start a cache server locally. Cache will be used to store the `self.last_modified` value inside it. If you don't have any cache installed, try installing redis cache. 
Follow this  guide to install and run it. 

> https://medium.com/@petehouston/install-and-config-redis-on-mac-os-x-via-homebrew-eb8df9a4f298

Once you do that add the following code into the settings file
```
CACHES = {
   "default": {
       "BACKEND": "django_redis.cache.RedisCache",
       "LOCATION": "redis://127.0.0.1:6379/1"
   }
}
```
This should do the job and hopefully you want see that error again if the cache is running properly and storing the key in your cache.

**Comment by brortao** [comment]
I'm getting this same error when calling `model_schema.as_model().objects.all()`.

It doesn't seem like installing a cache gets at the root of this problem.
