### ISSUE TITLE
makemigrations error!

### ISSUE THREAD

**Issue by idoing82** [rvinzent/django-dynamic-models#2]
>python manage.py makemigrations
Traceback (most recent call last):
  File "manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "d:\Anaconda3\envs\python37\lib\site-packages\django\core\management\__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "d:\Anaconda3\envs\python37\lib\site-packages\django\core\management\__init__.py", line 357, in execute
    django.setup()
  File "d:\Anaconda3\envs\python37\lib\site-packages\django\__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "d:\Anaconda3\envs\python37\lib\site-packages\django\apps\registry.py", line 93, in populate
    "duplicates: %s" % app_config.label)
django.core.exceptions.ImproperlyConfigured: Application labels aren't unique, duplicates: contenttypes

**Comment by brandonrobertz** [comment]
You added `django.contrib.contenttypes` package twice to your `INSTALLED_APPS`. The documentation here is a bit outdated as that package comes default in `settings.py` now in Django.

**Comment by rvinzent** [comment]
@brandonrobertz @idoing82  Agreed. The docs could be clearer. I have been a little busy for this project recently, but due to recent interest I will probably put some more time into this soon and clean up the docs, set up CI builds, etc.

Closing this for now as it seems to be resolved.
